# Dependabot version updates configuration.
# See docs: https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    versioning-strategy: increase
    groups:
      python-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 3

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      actions-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 3
