meta:
  case_id: case_0005
  benchmark_type: stereo-imaging
  seed: 46
  horizon_start: '2025-07-17T12:00:00Z'
  horizon_end: '2025-07-21T12:00:00Z'
stereo_imaging:
  target_ids:
  - city_ban_sai_ma_tai_th
  - city_laiwu_cn
  - city_escalante_ph
  - city_samarinda_id
  - city_mojokerto_id
  - city_mildura_au
  - city_al_manaqil_sd
  - city_kurivikod_in
  - city_ano_liosia_gr
  - city_ivirgarzama_bo
  - city_cusco_pe
  - city_mogi_das_cruzes_br
  - city_shreveport_us
  - city_south_san_francisco_us
  - city_san_jeronimo_gt
  - city_valladolid_es
  - city_akron_us
  - city_ibarra_ec
  - city_oullins_fr
  - city_vyshniy_volochek_ru
  - city_semiluki_ru
  - city_antalaha_mg
  - city_mahambo_mg
  - city_sumbe_ao
  - city_bangor_gb
  - city_bridlington_gb
  - city_stratford_gb
  - city_shuangcheng_cn
  - city_ulan_ude_ru
  - city_linkou_cn
  - city_moose_jaw_ca
  - city_vancouver_us
  - city_leduc_ca
  - city_coyhaique_cl
  - city_caleta_olivia_ar
  - city_ushuaia_ar
  - city_nuku_alofa_to
  - city_papeete_pf
  - city_apia_ws
  - city_invercargill_nz
  - city_dunedin_nz
  - city_ganderkesee_de
  - city_pilibangan_in
  min_azimuth_sep_deg: 15.0
  max_azimuth_sep_deg: 60.0
  max_time_between_obs_hours: 2.0
  min_elevation_deg: 30.0
  required_observations:
    city_ban_sai_ma_tai_th: 2
    city_laiwu_cn: 2
    city_escalante_ph: 2
    city_samarinda_id: 2
    city_mojokerto_id: 2
    city_mildura_au: 2
    city_al_manaqil_sd: 2
    city_kurivikod_in: 2
    city_ano_liosia_gr: 2
    city_ivirgarzama_bo: 2
    city_cusco_pe: 2
    city_mogi_das_cruzes_br: 2
    city_shreveport_us: 2
    city_south_san_francisco_us: 2
    city_san_jeronimo_gt: 2
    city_valladolid_es: 2
    city_akron_us: 2
    city_ibarra_ec: 2
    city_oullins_fr: 2
    city_vyshniy_volochek_ru: 2
    city_semiluki_ru: 2
    city_antalaha_mg: 2
    city_mahambo_mg: 2
    city_sumbe_ao: 2
    city_bangor_gb: 2
    city_bridlington_gb: 2
    city_stratford_gb: 2
    city_shuangcheng_cn: 2
    city_ulan_ude_ru: 2
    city_linkou_cn: 2
    city_moose_jaw_ca: 2
    city_vancouver_us: 2
    city_leduc_ca: 2
    city_coyhaique_cl: 2
    city_caleta_olivia_ar: 2
    city_ushuaia_ar: 2
    city_nuku_alofa_to: 2
    city_papeete_pf: 2
    city_apia_ws: 2
    city_invercargill_nz: 2
    city_dunedin_nz: 2
    city_ganderkesee_de: 2
    city_pilibangan_in: 2
