meta:
  case_id: case_0002
  benchmark_type: stereo-imaging
  seed: 43
  horizon_start: '2025-07-17T12:00:00Z'
  horizon_end: '2025-07-21T12:00:00Z'
stereo_imaging:
  target_ids:
  - city_qincheng_cn
  - city_cinere_id
  - city_multai_in
  - city_cerquilho_velho_br
  - city_manhattan_us_1
  - city_grand_lahou_ci
  - city_mariupol_ua
  - city_kilosa_tz
  - city_salaberry_de_valleyfield_ca
  - city_darhan_mn
  - city_edmonton_ca
  - city_ushuaia_ar
  - city_apia_ws
  - city_dunedin_nz
  - city_sumilao_ph
  min_azimuth_sep_deg: 15.0
  max_azimuth_sep_deg: 60.0
  max_time_between_obs_hours: 2.0
  min_elevation_deg: 30.0
  required_observations:
    city_qincheng_cn: 2
    city_cinere_id: 2
    city_multai_in: 2
    city_cerquilho_velho_br: 2
    city_manhattan_us_1: 2
    city_grand_lahou_ci: 2
    city_mariupol_ua: 2
    city_kilosa_tz: 2
    city_salaberry_de_valleyfield_ca: 2
    city_darhan_mn: 2
    city_edmonton_ca: 2
    city_ushuaia_ar: 2
    city_apia_ws: 2
    city_dunedin_nz: 2
    city_sumilao_ph: 2
