meta:
  case_id: case_0003
  benchmark_type: regional-coverage
  seed: 44
  horizon_start: '2025-07-17T12:00:00Z'
  horizon_end: '2025-07-21T12:00:00Z'
regional_coverage:
  polygons:
  - id: sahara_east
    vertices:
    - - 20.0
      - 15.0
    - - 20.0
      - 30.0
    - - 30.0
      - 30.0
    - - 30.0
      - 15.0
  - id: arabian_peninsula
    vertices:
    - - 15.0
      - 43.0
    - - 12.0
      - 50.0
    - - 18.0
      - 55.0
    - - 22.0
      - 52.0
    - - 20.0
      - 45.0
  - id: great_lakes
    vertices:
    - - 42.0
      - -84.0
    - - 44.0
      - -82.0
    - - 48.0
      - -84.0
    - - 48.0
      - -88.0
    - - 45.0
      - -90.0
    - - 42.0
      - -87.0
