meta:
  case_id: case_0001
  benchmark_type: stereo-imaging
  seed: 42
  horizon_start: '2025-07-17T12:00:00Z'
  horizon_end: '2025-07-21T12:00:00Z'
stereo_imaging:
  target_ids:
  - city_pontevedra_ph_1
  - city_taihe_cn
  - city_hengshui_cn
  - city_pangkalan_bun_id
  - city_indramayu_id
  - city_adonara_id
  - city_al_qurayyat_sa
  - city_tarrasa_es
  - city_perumbalam_in
  - city_careiro_br
  - city_sao_miguel_do_guama_br
  - city_divinopolis_br
  - city_lawndale_us
  - city_salina_us
  - city_des_moines_us
  - city_lisbon_pt
  - city_seixal_pt
  - city_panzos_gt
  - city_veszprem_hu
  - city_boxmeer_nl
  - city_bryansk_ru
  - city_same_tz
  - city_gitega_bi
  - city_giyani_za
  - city_wokingham_gb
  - city_accrington_gb
  - city_inverness_gb
  - city_mositai_cn
  - city_beian_cn
  - city_kansk_ru
  - city_tumwater_us
  - city_great_falls_us
  - city_vancouver_ca
  - city_caleta_olivia_ar
  - city_punta_arenas_cl
  - city_rio_gallegos_ar
  - city_apia_ws
  - city_nuku_alofa_to
  - city_papeete_pf
  - city_invercargill_nz
  - city_dunedin_nz
  - city_dongning_cn
  - city_qostanay_kz
  - city_grabouw_za
  - city_toledo_ph
  min_azimuth_sep_deg: 15.0
  max_azimuth_sep_deg: 60.0
  max_time_between_obs_hours: 2.0
  min_elevation_deg: 30.0
  required_observations:
    city_pontevedra_ph_1: 2
    city_taihe_cn: 2
    city_hengshui_cn: 2
    city_pangkalan_bun_id: 2
    city_indramayu_id: 2
    city_adonara_id: 2
    city_al_qurayyat_sa: 2
    city_tarrasa_es: 2
    city_perumbalam_in: 2
    city_careiro_br: 2
    city_sao_miguel_do_guama_br: 2
    city_divinopolis_br: 2
    city_lawndale_us: 2
    city_salina_us: 2
    city_des_moines_us: 2
    city_lisbon_pt: 2
    city_seixal_pt: 2
    city_panzos_gt: 2
    city_veszprem_hu: 2
    city_boxmeer_nl: 2
    city_bryansk_ru: 2
    city_same_tz: 2
    city_gitega_bi: 2
    city_giyani_za: 2
    city_wokingham_gb: 2
    city_accrington_gb: 2
    city_inverness_gb: 2
    city_mositai_cn: 2
    city_beian_cn: 2
    city_kansk_ru: 2
    city_tumwater_us: 2
    city_great_falls_us: 2
    city_vancouver_ca: 2
    city_caleta_olivia_ar: 2
    city_punta_arenas_cl: 2
    city_rio_gallegos_ar: 2
    city_apia_ws: 2
    city_nuku_alofa_to: 2
    city_papeete_pf: 2
    city_invercargill_nz: 2
    city_dunedin_nz: 2
    city_dongning_cn: 2
    city_qostanay_kz: 2
    city_grabouw_za: 2
    city_toledo_ph: 2
