meta:
  case_id: case_0001
  benchmark_type: regional-coverage
  seed: 42
  horizon_start: '2025-07-17T12:00:00Z'
  horizon_end: '2025-07-21T12:00:00Z'
regional_coverage:
  polygons:
  - id: amazon_north
    vertices:
    - - 0.0
      - -60.0
    - - 0.0
      - -50.0
    - - -5.0
      - -50.0
    - - -5.0
      - -60.0
  - id: gulf_of_mexico
    vertices:
    - - 30.0
      - -97.0
    - - 25.0
      - -95.0
    - - 20.0
      - -90.0
    - - 25.0
      - -85.0
    - - 30.0
      - -88.0
  - id: bay_of_bengal
    vertices:
    - - 22.0
      - 88.0
    - - 20.0
      - 94.0
    - - 15.0
      - 97.0
    - - 8.0
      - 95.0
    - - 10.0
      - 88.0
    - - 15.0
      - 85.0
