meta:
  case_id: case_0005
  benchmark_type: regional-coverage
  seed: 46
  horizon_start: '2025-07-17T12:00:00Z'
  horizon_end: '2025-07-21T12:00:00Z'
regional_coverage:
  polygons:
  - id: amazon_north
    vertices:
    - - 0.0
      - -60.0
    - - 0.0
      - -50.0
    - - -5.0
      - -50.0
    - - -5.0
      - -60.0
  - id: horn_of_africa
    vertices:
    - - 12.0
      - 43.0
    - - 10.0
      - 51.0
    - - 2.0
      - 48.0
    - - 5.0
      - 42.0
    - - 10.0
      - 40.0
  - id: great_lakes
    vertices:
    - - 42.0
      - -84.0
    - - 44.0
      - -82.0
    - - 48.0
      - -84.0
    - - 48.0
      - -88.0
    - - 45.0
      - -90.0
    - - 42.0
      - -87.0
